name: canopy
channels:
  - conda-forge
  - nodefaults
dependencies:
  - ipykernel
  - rasterio
  - folium
  - python=3.12
  - tqdm
  - matplotlib-base
  - mapclassify
  - geopandas
  - jupyterlab
  - numpy
  - pytorch-cpu
  - rasterstats
  - ipywidgets

